export const CREATED_NEW_TODO = "CREATED_NEW_TODO";
export const TODO_COMPLETION_TOGGLED = "TODO_COMPLETION_TOGGLED";
export const TODO_REMOVED = "TODO_REMOVED";
export const TOGGLE_ALL = "TOGGLE_ALL";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
export const START_EDITING = "START_EDITING";
export const END_EDITING = "END_EDITING";